[build]
  command = "ng build --configuration=production"
  functions = "netlify/functions"
  publish = "dist/exchange-dashboard/browser"

[[plugins]]
  package = "@netlify/plugin-inline-functions-env"
